# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Kevin Hong
tagline:             'Life is like a dream'
description:         'Supported by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> and <a href="https://github.com/poole/lanyon" target="_blank">lanyon</a>.'
url:                 http://lanyon.getpoole.com
baseurl:             ''
baseurl_l:		  	 'http://127.0.0.1:4000'
baseurl_r:		 	 'http://honqging.github.io'
paginate:            5
paginate_path:		 "page:num"

# About/contact
author:
  name:              Kevin Hong
  url:               https://twitter.com/
  email:             hhhhhhh@gmail.com
  photo:			 /public/img/aliaiti.jpeg

# Custom vars
version:             1.0.0

# Gems
gems: 				 [jekyll-paginate]
gems: 				 [jekyll-paginate, jekyll-gist]
